@startuml DiagrammaSequenzaMettiCuore

actor Autore
participant Interfaccia
participant Poesia
participant Cuore

' Stile del diagramma
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true

' Processo per mettere un cuore/like
Autore -> Interfaccia : 1: mettiCuore()
Interfaccia -> Poesia : 1.1: mettiCuore()

activate Poesia
Poesia -> Poesia : 1.1.1: verificaCuore
Poesia --> Interfaccia : 1.1.2: esito

' Gestione flusso alternativo
alt [if esito == false]
    ' Aggiunta di un cuore
    Poesia --> Cuore : 1.1.3: mettiCuore()
    
    ' Qui non c'è un ritorno esplicito dal Cuore alla Poesia nel diagramma originale
else
    ' Rimozione del cuore se esiste già
    Poesia -> Cuore : 1.1.4: rimuoviCuore
    destroy Cuore
end
deactivate Poesia

@enduml
