@startuml DiagrammaSequenzaLogin

actor UtenteRegistrato
participant Sistema

' Stile del diagramma
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true

' Loop per i tentativi di accesso
loop [1,*|ErroreCredenziali]]
    UtenteRegistrato -> Sistema : 1: accedi(email,password)
    
    activate Sistema
    Sistema -> Sistema : 1.1: verificaCredenziali(email,password)
    
    ' Gestione esito autenticazione
    alt [if esito == true]
        Sistema --> UtenteRegistrato : 1.2: confermaAutenticazione
    else
        Sistema --> UtenteRegistrato : 1.3: erroreCredenziali
    end
    deactivate Sistema
end

@enduml
