@startuml DiagrammaSequenzaRegistrazione

actor UtenteNonRegistrato
participant Interfaccia
participant Sistema
participant UtenteRegistrato
participant Profilo

' Stile del diagramma
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true

' Processo principale di registrazione
UtenteNonRegistrato -> Interfaccia : 2: registra(nome,cognome,email,password)
Interfaccia -> Sistema : 1: registra(nome,cognome,email,password)

activate Sistema
Sistema -> Sistema : 1.1: verificaDati
Sistema --> Interfaccia : 1.2: esito
deactivate Sistema

' Gestione flusso alternativo (fallimento)
alt if (esito==false)
    Interfaccia --> UtenteNonRegistrato : 3: ERROR Dati Incorretti
else
    ' Gestione flusso principale (successo)
    Sistema --> UtenteRegistrato : 1.3: crea
    UtenteRegistrato -> Profilo : 4: crea
    Profilo --> UtenteRegistrato : 6: return PROFILO
    UtenteRegistrato --> Sistema : 5: return UTENTEREGISTRATO
    Sistema --> Interfaccia : 1.4: utente è stato registrato
end

@enduml
