@startuml DiagrammaSequenzaCreaRaccolta

actor Autore
participant "Interfaccia" as UI
participant "Sistema" as System
participant "Raccolta" as Collection

' Stile del diagramma
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true

' Processo per creare una nuova raccolta
Autore -> UI : vuole aggiungere poesia a nuova raccolta
UI --> Autore : mostra form creazione raccolta

Autore -> UI : inserisce titolo e descrizione
Autore -> UI : salva la raccolta
UI -> System : creaRaccolta(titolo, descrizione)

activate System
System -> Collection : <<create>>
note right: Una nuova raccolta viene creata nel sistema
System --> UI : confermaCreazione()
deactivate System

UI --> Autore : mostra conferma creazione raccolta

@enduml
